### ISSUE TITLE
List repo on nio-template

### ISSUE THREAD

**Issue by anoadragon453** [TheForcer/vision-nio#1]
Hello there! You're one of the first repos to use my template!

Would you like to be listed on the template's README file?

Also, if you have any issues, do open an issue on the template page or contact me in [#nio-template:amorgan.xyz](https://matrix.to/#/!vmWBOsOkoOtVHMzZgN:amorgan.xyz?via=amorgan.xyz&via=matrix.org&via=t2l.io). Thanks!

**Comment by TheForcer** [comment]
Feel free to add the repo to your list. Just updated stuff so now would be a good time :)

**Comment by anoadragon453** [comment]
Thanks, added!
